'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import styles from './game-beta.module.css';
const HOST=process.env.NEXT_PUBLIC_CITY_GAME_ORIGIN||'https://jogo.alexandrevrabandonada.online';
type Release={buildId:string;version:string;saveSchema:number;releasedAt:string;notes:string[];limits:string[]};
function technical(release:Release|null){const ua=navigator.userAgent;return {game:'VR: Cidade em Disputa',buildId:release?.buildId||'unknown-beta',browser:/Firefox/.test(ua)?'Firefox':/Edg/.test(ua)?'Edge':/Chrome/.test(ua)?'Chrome':/Safari/.test(ua)?'Safari':'Other',platform:/Android/.test(ua)?'Android':/iPhone|iPad/.test(ua)?'iOS':/Windows/.test(ua)?'Windows':/Mac/.test(ua)?'macOS':'Other',viewport:`${innerWidth}×${innerHeight}`,webgl:!!document.createElement('canvas').getContext('webgl2'),saveSchema:release?.saveSchema,timestamp:new Date().toISOString()};}
export default function GameBeta(){
 const [release,setRelease]=useState<Release|null>(null),[history,setHistory]=useState<Release[]>([]),[started,setStarted]=useState(false),[status,setStatus]=useState('idle'),[progress,setProgress]=useState(0),[attempt,setAttempt]=useState(0),[feedback,setFeedback]=useState('problem'),[message,setMessage]=useState(''),[notice,setNotice]=useState(''),[sending,setSending]=useState(false);
 const container=useRef<HTMLDivElement>(null),frame=useRef<HTMLIFrameElement>(null),began=useRef(0),ready=useRef(false);
 function event(name:string,r=release,durationBucket=''){if(!r)return;void fetch('/api/game-beta',{method:'POST',headers:{'Content-Type':'application/json'},keepalive:true,body:JSON.stringify({kind:'metric',event:name,buildId:r.buildId,deviceClass:innerWidth<700?'mobile':'desktop',viewportClass:innerWidth<700?'small':innerWidth<1400?'medium':'large',durationBucket})}).catch(()=>{});}
 useEffect(()=>{let active=true;fetch(`${HOST}/release.json`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(r=>{if(active){setRelease(r);event('game_page_view',r);}}).catch(()=>{if(active)setNotice('As informações da versão estão temporariamente indisponíveis.');});fetch(`${HOST}/releases.json`,{cache:'no-store'}).then(r=>r.json()).then(r=>{if(active&&Array.isArray(r))setHistory(r);}).catch(()=>{});return()=>{active=false;};
 // Only version metadata is requested before start. No Unity resource, iframe or preconnect.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 useEffect(()=>{function receive(e:MessageEvent){if(e.origin!==HOST||e.source!==frame.current?.contentWindow||e.data?.source!=='vr-city')return;
  if(e.data.type==='progress'){setProgress(Math.max(0,Math.min(1,Number(e.data.progress)||0)));}
  if(e.data.type==='ready'){ready.current=true;setStatus('ready');event('load_success');}
  if(e.data.type==='error'){setStatus('error');event('load_error');}
 }window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[release]);
 useEffect(()=>{if(!started)return;const id=setTimeout(()=>{if(!ready.current){setStatus('error');event('load_error');}},180000);return()=>clearTimeout(id);
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[started,attempt]);
 useEffect(()=>{function end(){if(!began.current)return;const seconds=(Date.now()-began.current)/1000;event('session_duration_bucket',release,seconds<60?'under_1m':seconds<300?'1_to_5m':seconds<1200?'5_to_20m':'over_20m');began.current=0;}window.addEventListener('pagehide',end);return()=>window.removeEventListener('pagehide',end);
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[release]);
 function start(){ready.current=false;began.current=Date.now();setStarted(true);setStatus('loading');setProgress(0);setAttempt(a=>a+1);event('play_start');}
 async function fullscreen(){try{if(container.current?.requestFullscreen)await container.current.requestFullscreen();else window.open(HOST,'_blank','noopener');}catch{window.open(HOST,'_blank','noopener');}}
 async function copy(){const text=JSON.stringify(technical(release),null,2);try{await navigator.clipboard.writeText(text);setNotice('Informações técnicas copiadas.');}catch{setNotice(text);}}
 async function submit(e:FormEvent){e.preventDefault();setSending(true);setNotice('');try{const t=technical(release);const r=await fetch('/api/game-beta',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'feedback',category:feedback,message,buildId:t.buildId,platform:t.platform,browser:t.browser,viewport:t.viewport})});if(!r.ok)throw Error();setMessage('');setNotice('Obrigado. Seu relato foi enviado à equipe do jogo.');}catch{setNotice('Não foi possível enviar agora. Seu texto foi mantido; tente novamente.');}finally{setSending(false);}}
 return <div className={styles.page}><header className={styles.heading}><Link href="/" className={styles.back}>← Voltar à home</Link><p className={styles.eyebrow}>BETA PÚBLICA · RPG URBANO</p><h1>VR: CIDADE EM DISPUTA</h1><p>Uma experiência RPG em desenvolvimento ambientada em uma interpretação de Volta Redonda.</p><div className={styles.facts}><span>Joga direto no navegador</span><span>Desktop e celular</span><span>Progresso salvo neste dispositivo</span></div></header>
 <div ref={container} className={styles.player} aria-label="Player de VR: Cidade em Disputa">
 {!started?<div className={styles.preload}><Image src="/game-beta/cidade.webp" fill priority sizes="100vw" alt="Captura real do RPG, com Alexandre na Praça Brasil, jardins e monumento"/><div className={styles.preloadCopy}><p>EXPLORE · INVESTIGUE · CONECTE</p><button className={styles.primary} onClick={start}>INICIAR JOGO</button><small>O download começa após o clique · cerca de 18 MB</small></div></div>:<><iframe key={attempt} ref={frame} title="VR: Cidade em Disputa — player" src={`${HOST}/`} onLoad={()=>frame.current?.contentWindow?.postMessage({source:'vr-city-wrapper'},HOST)} allow="fullscreen" allowFullScreen referrerPolicy="no-referrer"/><div className={styles.loading} hidden={status!=='loading'} role="status" aria-live="polite">CARREGANDO A CIDADE <progress max={1} value={progress}/><span>{Math.round(progress*100)}%</span></div><div className={styles.failure} hidden={status!=='error'} role="alert"><h2>O jogo não conseguiu iniciar neste navegador.</h2><p>Confira a conexão ou abra em uma nova janela.</p><button onClick={start}>Tentar novamente</button><a href={HOST} target="_blank" rel="noopener">Abrir em nova janela</a><button onClick={copy}>Copiar diagnóstico</button></div></>}
 </div><div className={styles.toolbar}><span>BETA · BUILD {release?.buildId||'consultando versão'}</span><button onClick={fullscreen}>ABRIR EM TELA CHEIA</button><a href={HOST} target="_blank" rel="noopener">Abrir em nova janela ↗</a></div><p className={styles.orientation}>No celular, a posição horizontal pode ampliar a visão. Você também pode jogar na vertical.</p>
 <section className={styles.instructions}><h2>Como jogar</h2><p>WASD move · Shift corre · E interage · N abre o caderno · P abre o telefone · Esc volta. No celular, use os controles na tela. Abra o menu para ajustar fonte, contraste e movimento.</p><p>Salve pelo menu ou F5 e carregue com F9. Os saves ficam neste navegador e dispositivo; apagar os dados do site ou usar navegação privada pode removê-los.</p></section>
 <section id="versao" className={styles.version}><div><p className={styles.eyebrow}>VERSÃO ATUAL</p><h2>{release?.version||'Beta pública'}</h2><p>Este jogo está sendo desenvolvido continuamente. Novas regiões, histórias e sistemas serão adicionados.</p></div><div><h3>O QUE HÁ NESTA BUILD</h3><ul>{(release?.notes||['Missão Zero e três casos de investigação.','Vila Santa Cecília, margem do Paraíba e serviços públicos.']).map(n=><li key={n}>{n}</li>)}</ul><h3>LIMITAÇÕES CONHECIDAS</h3><ul>{(release?.limits||['Desempenho pode variar por celular.','Testes em aparelhos físicos estão sendo ampliados.']).map(n=><li key={n}>{n}</li>)}</ul></div></section>
 <section className={styles.instructions}><h2>O QUE MUDOU</h2>{history.slice(0,4).map(r=><details key={r.buildId}><summary>{r.version} · {r.buildId}</summary><ul>{r.notes.map(n=><li key={n}>{n}</li>)}</ul></details>)}{!history.length&&<p>O histórico de versões aparecerá aqui quando estiver disponível.</p>}</section>
 <section className={styles.feedback} id="feedback"><div><p className={styles.eyebrow}>AJUDE A MELHORAR O JOGO</p><h2>Conte como foi.</h2><p>Feedback anônimo. Não envie dados pessoais ou informações de outras pessoas.</p><p>Coletamos apenas categoria, relato, build, sistema, família do navegador e tamanho da tela. Métricas técnicas são agregadas; escolhas e decisões dentro do RPG não são enviadas nem usadas para perfil político.</p><button onClick={copy}>COPIAR INFORMAÇÕES TÉCNICAS</button></div><form onSubmit={submit}><fieldset><legend>Tipo de relato</legend><label><input type="radio" name="category" checked={feedback==='problem'} onChange={()=>setFeedback('problem')}/> REPORTAR UM PROBLEMA</label><label><input type="radio" name="category" checked={feedback==='experience'} onChange={()=>setFeedback('experience')}/> CONTAR COMO FOI</label></fieldset><label htmlFor="beta-message">Seu relato</label><textarea id="beta-message" minLength={10} maxLength={4000} required value={message} onChange={e=>setMessage(e.target.value)} placeholder="O que aconteceu? Em qual tela?"/><button className={styles.primary} disabled={sending}>{sending?'ENVIANDO…':'ENVIAR RELATO'}</button><p role="status" className={styles.notice}>{notice}</p></form></section></div>;
}
